### ISSUE TITLE
BathBlimp

### ISSUE THREAD

**Issue by PauloAlmas** [arramus/Snufkin-Community-Pack-Server-Side-Vehicles-A19-Stable-2020Nov2#1]
Hello again : 

How to chance the velocity of BathBlimp, too fast to put on servers will lag, what field i have to change to slower them down like gyroscope ?

Is easy to make a motorcycle Bath for donor ?

Tanks

**Comment by arramus** [comment]
The Bath Blimp copied the Shark Blimp by oakraven. But it is probably this setting for regular and boost speed.

vehicles.xml

gyro value is:
		<property name="velocityMax" value="9, 15"/>

Bath Blimp is:
		<property name="velocityMax" value="10, 18"/>

Requests are usually placed on the main forum page so modders can discuss it. Github is used for sharing but rarely discussion. https://community.7daystodie.com/topic/22357-snufkins-community-pack-server-side-vehicles/

**Comment by PauloAlmas** [comment]
Tanks

Posted there ;)
